# Generated by Django 5.2.15 on 2026-06-29 19:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('very_low', 'Very low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very high')], default='low', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['due_date'], name='project_due_date_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='project_tags_gin_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('very_low', 'Very low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very high')], default='low', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='task_project_id_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='task_tags_gin_idx')],
            },
        ),
    ]
