# Generated by Django 5.2.15 on 2026-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='soonest_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['soonest_due_date'], name='project_soonest_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
    ]
